var sentences = new Array(

    "”The <em ><a style='color:orange' href='games/halflife/index.html'>right man</a></em> in the wrong place can make all the difference in the world.”",
    "Duck approved!",
    "Don't do drugs kids!",
    "Also check out <a href='https://mesa.rip'>Mesacomplex</a>",
    "Monke Funni",
    "<h1><strong><em>E</h1></strong></em>",
    "”All right, I've been thinking, when life gives you lemons, don't make lemonade! Make life take the lemons back! Get Mad! I don't want your damn lemons! What am I supposed to do with these? Demand to see life's manager! Make life rue the day it thought it could give Cave Johnson lemons! Do you know who I am? I'm the man whose gonna burn your house down - with the lemons! I'm gonna get my engineers to invent a combustible lemon that'll burn your house down!”",
    "”Wake up Mister Freeman, Wake up and ... Smell the ashes”",
    "“<strong>FINISH HIM!</strong>”",
    "“Most test subjects do experience some cognitive deterioration after a few months in suspension. Now you’ve been under for… quite a lot longer, and it’s not out of the question that you might have a very minor case of serious brain damage. But don’t be alarmed, alright? Although, if you do feel alarmed, try to hold onto that feeling because that is the proper reaction to being told you have brain damage.”",
    "“It’s dangerous to go alone, take this!”",
    "“Stop right there, criminal scum!”",
    "“I used to be an adventurer like you until I took an arrow to the knee.”",
    " “Do a barrel roll!”",
    "“Grass grows, birds fly, the sun shines, and brother, I hurt people.”",
    "“Thank you, Mario! But our Princess is in another castle!”",
    "“You have died of dysentery.”",
    "“At the end of the day, as long as there are two people left on the planet, someone is gonna want someone dead.”",
    "“I like shorts! They’re comfy and easy to wear!”",
    "“DEATH IS A PREFERABLE ALTERNATIVE TO COMMUNISM”",
    "“Oh. Hi. So. How are you holding up? BECAUSE I'M A POTATO“",
    "“GLaDOS:<br>[Chell and GLaDOS, as a potato, are flying toward Wheatley, into a trap] Aaaah!<br>GLaDOS:<br>[On a platform, surrounded with spiked stompers] Well, this is the part where he kills us.<br>Wheatley:<br>This is the part where I kill you!<br>[On-Screen caption:<br>Chapter 9: the Part Where He Kills You]<br>Wheatley:<br>[Achievement unlocked: the part where he kills you. This is that part]“",
    "“I feel awful about that surprise. Tell you what, let's give your parents a call right now. [phone dialing and ringing; in a stranger, lower voice] The birth parents you are trying to reach do not love you. Please hang up. [Dial tone; normal voice] Oh, that's sad. But impressive. Maybe they worked at the phone company.“",
    "“I see, your HEV-Suit still fits you like a glove. At least the glove parts do.“",
    "“It's more important to master the cards you're holding than to complain about the ones your opponent was dealt.“",
    "“Courage need not be remembered, for it is never forgotten!“",
    "“Don't wish it were easier, wish you were better.“",
    "“The best solution to a problem is usually the easiest one!“",
    "“Life is a serious battle, and you have to use the tools you're given.“",
    "“I'd like to play a video game where you help the people who were shot in all the other games. It'd be called 'Really Busy Hospital“ - Demetri Martin",
    "“If Pac-Man had affected us as kids, we'd all be running around in dark rooms, munching pills and listening to repetitive electronic music.“ - Marcus Brigstocke",
    "“My parents said that sitting at home playing video games all day won't bring you anywhere in life.“ - PewDiePie",
    "“Reality is broken. Game designers can fix it.“ - Jane McGonigal",
    "“Against all the evil that Hell can conjure, all the wickedness that mankind can produce, we will send unto them ... only you. <em id='doom' style='color:red'>Rip and tear</em>, until it is done.“",
    "“Men are but flesh and blood. They know their doom, but not the hour.“",
    "“Science isn't about why - it's about why not.“",
    "“Remember to tell your grandkids to put a rocket launcher in your coffin. If you go to Hell when you die, you’ll need it for some final cleaning-up...“",
    "“War. War never changes“",
    "“I've a feeling we're not in Kansas anymore“",
    "“May The Force be with you.“",
    "“I feel the need, the need for speed!“",
    "Bond. James Bond.",
    "Up+Up+Down+Down+Left+Right+Left+Right+B+A+Start",
    "<a href='https://www.youtube.com/watch?v=dQw4w9WgXcQ'>OOoOoOOOoO YOU GOT LUCKYY, NOW YOU CAN PLAY GTA, FORTNITE, RUST, AND CALL OF DUTY JUST CLICK HERE!1!1!!!!</a>",
    "“Stop it, get some help“",
    "Yeet",
    "STOP POSTING ABOUT AMONG US!!!!",
    "Ihay Owhay Areay Ouyay?",
    "“<strong><em>I'M BATMAN</em></strong>“ - Batman(no shit)",
    "Don't be mean to nerds, they'll rule the world one day and be mean to you :)",
    "Cartoons are cool, if you think you are too old for them then you are crazy.",
    "Bro stfu Green Day is good",
    "BE GAY, DO CRIME",
    "PEOPLE ARE PEOPLE NO MATTER THEIR INTRESTS, LOOKS, OR HOW THEY IDENTIFY",
    "LOVE IS LOVE <3",
    "UwU",
    "Ngl the <em id='doom' style='color:red'>DOOM</em> soundtrack slaps",
    "Please do your work before playing games, YES, I'M LOOKING AT YOU 0_0",
    "DO YOUR DISHES!!!",
    "“Quote“",
    "“SPAAAAAAAAAAAAAAAAAAAAAAAAAAAACE!!!“",
    "omg its snas undertable",
    "*The <em id='doom' style='color:red'>DOOM</em> music kicks in*",
    "<h2 style='font-family:Arial'>( ͡° ͜ʖ ͡°)</h2>",
    "OMG WALTER WHITE LOOKS LIKE GORDOT FEETMAN FR FR ONG !!!1!1111!!1111!11",
    "EA SPORTS, IT'S IN THE GAME",
    "gameing(){<br>if(bored=true){<br>playgames = 'do now'<br>}<br>}",
    "I ran out of ideas",
    "aaaaa",
    "YeeHaw",
    "what",
    "So you're saying theres a chance?",
    "ahahahhahahhhahhahahha",
    "<p>░░░░░▄▄▄▄▀▀▀▀▀▀▀▀▄▄▄▄▄▄░░░░░░░<br>░░░░░█░░░░▒▒▒▒▒▒▒▒▒▒▒▒░░▀▀▄░░░░<br>░░░░█░░░▒▒▒▒▒▒░░░░░░░░▒▒▒░░█░░░<br>░░░█░░░░░░▄██▀▄▄░░░░░▄▄▄░░░░█░░<br>░▄▀▒▄▄▄▒░█▀▀▀▀▄▄█░░░██▄▄█░░░░█░<br>█░▒█▒▄░▀▄▄▄▀░░░░░░░░█░░░▒▒▒▒▒░█<br>█░▒█░█▀▄▄░░░░░█▀░░░░▀▄░░▄▀▀▀▄▒█<br>░█░▀▄░█▄░█▀▄▄░▀░▀▀░▄▄▀░░░░█░░█░<br>░░█░░░▀▄▀█▄▄░█▀▀▀▄▄▄▄▀▀█▀██░█░░<br>░░░█░░░░██░░▀█▄▄▄█▄▄█▄████░█░░░<br>░░░░█░░░░▀▀▄░█░░░█░█▀██████░█░░<br>░░░░░▀▄░░░░░▀▀▄▄▄█▄█▄█▄█▄▀░░█░░<br>░░░░░░░▀▄▄░▒▒▒▒░░░░░░░░░░▒░░░█░<br>░░░░░░░░░░▀▀▄▄░▒▒▒▒▒▒▒▒▒▒░░░░█░<br>░░░░░░░░░░░░░░▀▄▄▄▄▄░░░░░░░░█░░</p>",
    "JOIN THE PC MASTER RACE",
    "Monke see Monke do",
    "i love u sophie <33",
    "Why is breaking bad actually a really good show"
    );